"""
Constantes do projeto: UFs, setores, i18n, etc.
"""

# Estados brasileiros em ordem alfabética
UF_ORDER = [
    "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA",
    "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN",
    "RS", "RO", "RR", "SC", "SP", "SE", "TO"
]

# Mapeamento estado completo -> UF
STATE_TO_UF = {
    "Acre": "AC", "Alagoas": "AL", "Amapa": "AP", "Amapá": "AP",
    "Amazonas": "AM", "Bahia": "BA", "Ceara": "CE", "Ceará": "CE",
    "Distrito Federal": "DF", "Espirito Santo": "ES", "Espírito Santo": "ES",
    "Goias": "GO", "Goiás": "GO", "Maranhao": "MA", "Maranhão": "MA",
    "Mato Grosso": "MT", "Mato Grosso do Sul": "MS", "Minas Gerais": "MG",
    "Para": "PA", "Pará": "PA", "Paraiba": "PB", "Paraíba": "PB",
    "Parana": "PR", "Paraná": "PR", "Pernambuco": "PE", "Piaui": "PI",
    "Piauí": "PI", "Rio de Janeiro": "RJ", "Rio Grande do Norte": "RN",
    "Rio Grande do Sul": "RS", "Rondonia": "RO", "Rondônia": "RO",
    "Roraima": "RR", "Santa Catarina": "SC", "Sao Paulo": "SP",
    "São Paulo": "SP", "Sergipe": "SE", "Tocantins": "TO",
}

# Mapeamento UF -> Região
UF_TO_REGION = {
    "AC": "Norte", "AL": "Nordeste", "AM": "Norte", "AP": "Norte",
    "BA": "Nordeste", "CE": "Nordeste", "DF": "Centro-Oeste",
    "ES": "Sudeste", "GO": "Centro-Oeste", "MA": "Nordeste",
    "MT": "Centro-Oeste", "MS": "Centro-Oeste", "MG": "Sudeste",
    "PA": "Norte", "PB": "Nordeste", "PR": "Sul", "PE": "Nordeste",
    "PI": "Nordeste", "RJ": "Sudeste", "RN": "Nordeste",
    "RS": "Sul", "RO": "Norte", "RR": "Norte", "SC": "Sul",
    "SP": "Sudeste", "SE": "Nordeste", "TO": "Norte",
}

# Macro-setores executivos
MACRO_SECTORS = [
    "Agronegócio",
    "Indústria",
    "Comércio",
    "Serviços",
    "Tecnologia",
]

# Internacionalização (PT + EN)
I18N = {
    "pt": {
        "title": "PAINEL B2B BRASIL — INTELIGÊNCIA DE MERCADO",
        "subtitle": "Empresas (IBGE 2008–2021) + Empregos (CAGED 2024–2025) + Índice Estrutural (IBGE 2021)",
        "controls": "CONTROLES",
        "source": "Fonte principal",
        "companies": "Empresas (IBGE 2008–2021)",
        "jobs": "Empregos (CAGED 2024–2025)",
        "uf": "Estado (UF)",
        "year": "Ano",
        "macro": "Macro-setor (executivo)",
        "macro_all": "(Todos)",
        "tech_only": "Somente Tecnologia (macro)",
        "debug": "Mostrar tabela (debug)",
        "tabs": ["📈 Visão Geral", "🏭 Macro-setores", "🧭 Visão Integrada", "🗺️ Mapa & Rankings", "💼 PNAD", "🧾 Dados"],
        "kpi_source": "Fonte",
        "kpi_indicator": "Indicador no recorte",
        "kpi_top_uf": "Top UF",
        "kpi_top_macro": "Top Macro-setor",
        "indicator_companies": "Saldo de empresas (aberturas - fechamentos)",
        "indicator_jobs": "Saldo de empregos (admissões - desligamentos)",
        "time_series": "Série temporal",
        "ranking_macro": "Ranking por macro-setor",
        "map_structural": "Índice Estrutural por UF (IBGE 2021)",
        "map_toggle_rank": "Mostrar ranking ao lado do mapa",
        "rank_title": "Ranking (IBGE 2021)",
        "map_story": "Destaques do recorte atual",
        "top_hiring_states": "Top UFs no recorte",
        "top_sectors_in_top_states": "Macro-setores líderes nessas UFs",
        "data_diag": "Diagnóstico + dados carregados",
        "insight": "Resumo executivo (automático)",
        "no_data": "Sem dados no recorte atual.",
        "lang": "Idioma",
        "en": "English",
        "pt_opt": "Português",
        "note_macro": "Macro-setores para leitura executiva (sem CNAE detalhado).",
        "map_title": "Índice Estrutural por Estado",
        "map_description": "Índice agregado (2021) que mede oportunidades econômicas estruturais por estado. **Maior = melhor oportunidade.** Fonte: IBGE / SIDRA",
        "map_col_rank": "Rank",
        "map_col_state": "Estado (UF)",
        "map_col_region": "Região",
        "map_col_index": "Índice Estrutural",
        "pnad_title": "Mercado de Trabalho (PNAD)",
        "pnad_desc": "Dados agregados da Pesquisa Nacional por Amostra de Domicílios Contínua (IBGE)",
        "pnad_year": "Ano",
        "pnad_state": "Estado",
        "pnad_gender": "Sexo",
        "pnad_age_group": "Faixa Etária",
        "pnad_population": "População",
        "pnad_filters": "Filtros",
        "pnad_data": "Dados PNAD",
        "pnad_not_found": "Arquivo PNAD não encontrado",
        "pnad_not_found_msg": "Execute 'python run_pnad_pipeline.py' para gerar o parquet",
        "pnad_time_series": "Série Temporal da População",
        "pnad_comparison": "Comparação por Estado",
        "pnad_metric_selector": "Seletor de Métrica",
        "pnad_select_metric": "Escolha a métrica para análise",
        "pnad_kpis": "KPIs",
        "pnad_informality": "Taxa de Informalidade",
        "pnad_income": "Renda Média do Trabalho",
        "pnad_unemployment": "Taxa de Desemprego",
    },
    "en": {
        "title": "BRAZIL B2B DASHBOARD — MARKET INTELLIGENCE",
        "subtitle": "Companies (IBGE 2008–2021) + Jobs (CAGED 2024–2025) + Structural Index (IBGE 2021)",
        "controls": "CONTROLS",
        "source": "Primary source",
        "companies": "Companies (IBGE 2008–2021)",
        "jobs": "Jobs (CAGED 2024–2025)",
        "uf": "State (UF)",
        "year": "Year",
        "macro": "Macro-sector (executive)",
        "macro_all": "(All)",
        "tech_only": "Tech only (macro)",
        "debug": "Show table (debug)",
        "tabs": ["📈 Overview", "🏭 Macro-sectors", "🧭 Integrated View", "🗺️ Map & Rankings", "💼 PNAD", "🧾 Data"],
        "kpi_source": "Source",
        "kpi_indicator": "Metric in current slice",
        "kpi_top_uf": "Top State",
        "kpi_top_macro": "Top Macro-sector",
        "indicator_companies": "Net companies (openings - closures)",
        "indicator_jobs": "Net jobs (hires - separations)",
        "time_series": "Time series",
        "ranking_macro": "Macro-sector ranking",
        "map_structural": "Structural Index by State (IBGE 2021)",
        "map_toggle_rank": "Show ranking next to the map",
        "rank_title": "Ranking (IBGE 2021)",
        "map_story": "Highlights (current slice)",
        "top_hiring_states": "Top states in this slice",
        "top_sectors_in_top_states": "Leading macro-sectors within those states",
        "data_diag": "Diagnostics + loaded datasets",
        "insight": "Executive summary (auto)",
        "no_data": "No data for the current slice.",
        "lang": "Language",
        "en": "English",
        "pt_opt": "Português",
        "note_macro": "Macro-sectors for executive reading (no detailed CNAE).",
        "map_title": "Structural Index by State",
        "map_description": "Aggregated structural index (2021) measuring economic opportunity by state. **Higher values indicate greater opportunity.** Source: IBGE / SIDRA",
        "map_col_rank": "Rank",
        "map_col_state": "State (UF)",
        "map_col_region": "Region",
        "map_col_index": "Structural Index",
        "pnad_title": "Labor Market (PNAD)",
        "pnad_desc": "Aggregated data from National Continuous Household Sample Survey (IBGE)",
        "pnad_year": "Year",
        "pnad_state": "State",
        "pnad_gender": "Gender",
        "pnad_age_group": "Age Group",
        "pnad_population": "Population",
        "pnad_filters": "Filters",
        "pnad_data": "PNAD Data",
        "pnad_not_found": "PNAD file not found",
        "pnad_not_found_msg": "Run 'python run_pnad_pipeline.py' to generate the parquet",
        "pnad_time_series": "Population Time Series",
        "pnad_comparison": "Comparison by State",
        "pnad_metric_selector": "Metric Selector",
        "pnad_select_metric": "Choose a metric for analysis",
        "pnad_kpis": "KPIs",
        "pnad_informality": "Informality Rate",
        "pnad_income": "Average Work Income",
        "pnad_unemployment": "Unemployment Rate",
    }
}
